name: Auto Label PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Label PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body.toLowerCase();
            const prTitle = pr.title.toLowerCase();
            
            // Add gssoc label to all PRs
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['gssoc']
            });
            
            // Check for documentation changes
            if (prBody.includes('documentation') || prTitle.includes('doc') || prBody.includes('readme')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['documentation']
              });
            }
            
            // Check for enhancements
            if (prBody.includes('feature') || prBody.includes('enhancement') || prTitle.includes('add') || prTitle.includes('implement')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['enhancement']
              });
            }
            
            // Check for bugs
            if (prBody.includes('bug') || prBody.includes('fix') || prTitle.includes('fix') || prTitle.includes('resolve')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['bug']
              });
            }
