name: Auto Label Issues

on:
  issues:
    types: [opened, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply GSSoC label
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              labels: ['GSSoC']
            })

      - name: Categorize issue
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            const body = issue.body.toLowerCase();
            
            let labels = [];
            
            if (title.includes('doc') || body.includes('doc') || title.includes('readme') || body.includes('readme')) {
              labels.push('documentation');
            }
            
            if (title.includes('feature') || body.includes('feature') || title.includes('enhance') || body.includes('enhance')) {
              labels.push('enhancement');
            }
            
            if (title.includes('bug') || body.includes('bug') || title.includes('fix') || body.includes('fix')) {
              labels.push('bug');
            }
            
            if (labels.length > 0) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.name,
                labels: labels
              });
            }
