name: Auto Label Issues
on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

name: "Auto Label"
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

.github/labeler.yml:
GSSOC:
  - '.*'
documentation:
  - '.README.'
  - '.docs.'
enhancement:
  - '.feature.'
  - '.enhance.'
bug:
  - '.bug.'
  - '.fix.'
  - '.issue.'
